import os;
env = Environment();
#env.Append( LINKFLAGS = Split('-z origin'));
env.Append( RPATH = env.Literal(os.path.join('\\$$ORIGIN'))); # os.path.join('\\$$ORIGIN','lib');

VariantDir('build', 'src', duplicate=0);

sources = Glob("build/*.cpp");
env.Program('#build/epplugd', sources, LIBS=["gcc_s", "gcc", "stdc++", "udev", "dns_sd", "epframework",  "pthread", "tjshared", 
"tinyxml", "oscpack", "tjscript", "tjnp", "tjscout"],  LIBPATH=['#build', '#Libraries/mDNS/Release'], 
CPPPATH=['#','#Libraries','#EP','#Core'], CCFLAGS="-DTJ_OS_LINUX -DTJ_OS_POSIX");
