# EPFramework build
VariantDir('build', 'src');
env = Environment();

sources = Glob("build/*.cpp");

objects = env.SharedObject(sources, CCFLAGS='-DTJ_OS_POSIX -DTJ_OS_LINUX', LIBS=['gcc','gcc_s','pthread','tjshared','tjnp','oscpack','tinyxml','tjscout']);
env.SharedLibrary('#build/epframework', objects);
